import { resetDb } from '../services/db.js';
import { normalizeSalesProduct } from '../services/salesNormalize.js';

const now = new Date().toISOString();

const SWITCH_INSTALL = {
  listPrice: '890.000đ',
  installationSteps: [
    'Bước 1: Ngắt nguồn điện tại aptomat trước khi thao tác.',
    'Bước 2: Tháo công tắc cũ, đấu dây L (pha) và N (nguội) vào cọc nguồn theo sơ đồ.',
    'Bước 3: Gắn thiết bị vào đế âm, vặn ốc vít chắc chắn.',
    'Bước 4: Bật điện và ghép nối qua app Smart Home.',
  ],
  wiringDiagramUrl:
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&fit=crop',
  dimensions: { widthMm: 86, heightMm: 86, depthMm: 34 },
  weightG: 118,
};

function p(data) {
  return normalizeSalesProduct({ ...data, createdAt: now, updatedAt: now });
}

const products = [
  p({
    id: 'prod-001',
    commercialSku: 'SH-GW-M3-GL',
    name: 'M3 Smart Gateway (Global)',
    systemRole: 'HUB_CENTRAL',
    productCategory: 'SWITCH',
    region: 'GLOBAL',
    protocol: 'MATTER',
    lifecycle: 'CASH_COW',
    activationRate: 92,
    offlineRate: 1.2,
    salesSpecs: { maxChildDevices: 256, powerPort: 'USB Type-C', ethernet: true },
    description: 'Hub điều phối Matter + Zigbee cho thị trường quốc tế',
  }),
  p({
    id: 'prod-002',
    commercialSku: 'SH-GW-M3-CN',
    name: 'M3 Gateway (China Domestic)',
    systemRole: 'HUB_CENTRAL',
    productCategory: 'SWITCH',
    region: 'MAINLAND_CHINA',
    protocol: 'ZIGBEE_3',
    lifecycle: 'CASH_COW',
    activationRate: 88,
    offlineRate: 2.8,
    salesSpecs: { maxChildDevices: 128, powerPort: 'Micro USB', ethernet: false },
    description: 'Phiên bản nội địa Trung Quốc',
  }),
  p({
    id: 'prod-003',
    commercialSku: 'SH-SW-1G-NN-EU',
    name: 'Công tắc 1 kênh No-Neutral EU',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SWITCH',
    region: 'EU',
    protocol: 'ZIGBEE_3',
    lifecycle: 'CASH_COW',
    activationRate: 81,
    offlineRate: 4,
    salesSpecs: { maxLoadW: 800, neutralWire: 'NO_NEUTRAL', mountType: 'RECTANGLE', channels: 1 },
    ...SWITCH_INSTALL,
    predecessorId: 'prod-004',
    description: 'Công tắc không dây nguội — EU',
  }),
  p({
    id: 'prod-004',
    commercialSku: 'SH-SW-1G-N-VN',
    name: 'Công tắc 1 kênh có Neutral VN',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SWITCH',
    region: 'VN',
    protocol: 'ZIGBEE_3',
    lifecycle: 'LEGACY',
    activationRate: 76,
    offlineRate: 5.6,
    salesSpecs: { maxLoadW: 600, neutralWire: 'WITH_NEUTRAL', mountType: 'SQUARE', channels: 1 },
    ...SWITCH_INSTALL,
    listPrice: '650.000đ',
    successorId: 'prod-003',
    description: 'Mẫu cũ — Sales chuyển khách sang No-N EU',
  }),
  p({
    id: 'prod-005',
    commercialSku: 'SH-SW-2G-N-US',
    name: 'Công tắc 2 kênh US',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SWITCH',
    region: 'US',
    protocol: 'ZIGBEE_3',
    lifecycle: 'RND',
    activationRate: 68,
    offlineRate: 3,
    salesSpecs: { maxLoadW: 1200, neutralWire: 'WITH_NEUTRAL', mountType: 'RECTANGLE', channels: 2 },
    description: 'Sắp ra mắt thị trường Mỹ',
  }),
  p({
    id: 'prod-006',
    commercialSku: 'SH-PIR-GL',
    name: 'Cảm biến chuyển động Pro',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SENSOR',
    region: 'GLOBAL',
    protocol: 'ZIGBEE_3',
    lifecycle: 'CASH_COW',
    activationRate: 90,
    offlineRate: 2,
    salesSpecs: { batteryType: 'CR2450', detectionRangeM: 7, sensorSubtype: 'Motion' },
    successorId: 'prod-007',
  }),
  p({
    id: 'prod-007',
    commercialSku: 'SH-PRES-GL',
    name: 'Cảm biến hiện diện mmWave',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SENSOR',
    region: 'GLOBAL',
    protocol: 'ZIGBEE_3',
    lifecycle: 'RND',
    activationRate: 54,
    offlineRate: 7,
    salesSpecs: { batteryType: 'USB-C', detectionRangeM: 6, sensorSubtype: 'Presence/Radar' },
    predecessorId: 'prod-006',
  }),
  p({
    id: 'prod-008',
    commercialSku: 'SH-CAM-G2-GL',
    name: 'Camera an ninh G2',
    systemRole: 'STANDALONE_CLOUD',
    productCategory: 'SECURITY',
    region: 'GLOBAL',
    protocol: 'WIFI',
    lifecycle: 'CASH_COW',
    activationRate: 94,
    offlineRate: 1.8,
    salesSpecs: { resolution: '2K', connectivity: 'Wi-Fi, BLE', nightVision: true },
    successorId: 'prod-009',
  }),
  p({
    id: 'prod-009',
    commercialSku: 'SH-CAM-G3-GL',
    name: 'Camera G3 Matter',
    systemRole: 'STANDALONE_CLOUD',
    productCategory: 'SECURITY',
    region: 'GLOBAL',
    protocol: 'MATTER',
    lifecycle: 'RND',
    activationRate: 42,
    offlineRate: 8,
    salesSpecs: { resolution: '4K', connectivity: 'Wi-Fi, Thread', nightVision: true },
    predecessorId: 'prod-008',
  }),
  p({
    id: 'prod-010',
    commercialSku: 'SH-LOCK-U300-EU',
    name: 'Khóa thông minh U300',
    systemRole: 'STANDALONE_CLOUD',
    productCategory: 'SECURITY',
    region: 'EU',
    protocol: 'BLE',
    lifecycle: 'CASH_COW',
    activationRate: 87,
    offlineRate: 2.4,
    salesSpecs: { resolution: '—', connectivity: 'BLE + Wi-Fi Bridge', nightVision: false },
  }),
  p({
    id: 'prod-011',
    commercialSku: 'SH-LIGHT-RGB-GL',
    name: 'Đèn thông minh RGB',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'LIGHTING',
    region: 'GLOBAL',
    protocol: 'ZIGBEE_3',
    lifecycle: 'CASH_COW',
    activationRate: 85,
    offlineRate: 2.5,
    salesSpecs: { lumens: 1100, wattageW: 12, colorMode: 'RGB' },
  }),
  p({
    id: 'prod-012',
    commercialSku: 'SH-SOCK-2P-VN',
    name: 'Ổ cắm thông minh 2 cổng',
    systemRole: 'PERIPHERAL_HUB',
    productCategory: 'SOCKET',
    region: 'VN',
    protocol: 'ZIGBEE_3',
    lifecycle: 'CASH_COW',
    activationRate: 79,
    offlineRate: 3.8,
    salesSpecs: { maxLoadW: 2500, neutralWire: 'WITH_NEUTRAL', mountType: 'RECTANGLE', usbPorts: 2 },
  }),
];

const serials = [
  {
    id: 'sn-001',
    serialNumber: 'CN2025GW0001001',
    skuId: 'prod-002',
    region: 'MAINLAND_CHINA',
    manufacturedAt: '2025-01-15T00:00:00.000Z',
    activated: false,
    activatedAt: null,
    activationServer: null,
    blocked: false,
    blockReason: null,
  },
  {
    id: 'sn-002',
    serialNumber: 'GL2025GW0002001',
    skuId: 'prod-001',
    region: 'GLOBAL',
    manufacturedAt: '2025-02-01T00:00:00.000Z',
    activated: true,
    activatedAt: '2025-02-10T08:00:00.000Z',
    activationServer: 'GLOBAL',
    blocked: false,
    blockReason: null,
  },
  {
    id: 'sn-003',
    serialNumber: 'CN2025SW0003001',
    skuId: 'prod-004',
    region: 'MAINLAND_CHINA',
    manufacturedAt: '2025-03-01T00:00:00.000Z',
    activated: false,
    activatedAt: null,
    activationServer: null,
    blocked: true,
    blockReason: 'China domestic unit — Global activation blocked',
  },
  {
    id: 'sn-004',
    serialNumber: 'VN2025SW0004001',
    skuId: 'prod-004',
    region: 'VN',
    manufacturedAt: '2025-03-15T00:00:00.000Z',
    activated: false,
    activatedAt: null,
    activationServer: null,
    blocked: false,
    blockReason: null,
  },
];

const activations = [];

async function seed() {
  await resetDb({ products, serials, activations });
  console.log(`Seeded ${products.length} sales products, ${serials.length} serials`);
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
